import streamlit as st
import os
import google.generativeai as genai
from google.generativeai.types import HarmCategory, HarmBlockThreshold
import creds

# Configure Gemini API with your key
genai.configure(api_key=creds.GEMINI_API_KEY)

# Title of the app
st.title("Election Prediction App")

# Instructions for developers
st.subheader("Election Predictions using Gemini AI Model")
st.write("This app uses Google's Gemini AI model for making predictions based on your input. Please provide relevant data for accurate election outcome predictions.")

# Configuration for the Generative Model
generation_config = {
    "temperature": 0,
    "top_p": 0.95,
    "top_k": 64,
    "max_output_tokens": 8192,
    "response_mime_type": "text/plain",
}

# Load the model
model = genai.GenerativeModel(
    model_name="gemini-1.5-flash-8b-exp-0827",
    generation_config=generation_config
)

# User input section
st.subheader("Input Election Data")
input_data = ("Use the given data only for output. Add an sentence in every response \"Source:https://www.ihp.lk/research-updates/changes-support-leading-presidential-candidates-during-2024-lead-campaign-period\".",
  "Question Who is currently leading in support among the candidates?",
  "Answer President Ranil Wickremesinghe is currently leading in support among the candidates.",
  "Question Who is in the second place according to the August 2024 MRP model estimates?",
  "Answer Sajith Premadasa is in second place according to the August 2024 MRP model estimates.",
  "Question Who is trailing in third place based on the MRP projections?",
  "Answer Anura Dissanayake is trailing in third place based on the MRP projections.",
  "Question Who is the current frontrunner in the voting intent projections?",
  "Answer President Ranil Wickremesinghe is the current frontrunner in the voting intent projections.",
  "Question Which candidate has the highest support among older voters (60+ years)?",
  "Answer President Ranil Wickremesinghe has the highest support among older voters (60+ years).",
  "Question Which candidate has the lowest support among voters aged 18–29 years?",
  "Answer Anura Dissanayake has the lowest support among voters aged 18–29 years.",
  "Question Who has the highest increase in support among women from January/February 2024 to June/July 2024?",
  "Answer President Ranil Wickremesinghe has the highest increase in support among women.",
  "Question Which candidate has experienced the largest drop in support among Sinhala voters?",
  "Answer Anura Dissanayake has experienced the largest drop in support among Sinhala voters.",
  "Question Who is the top candidate among poor voters based on the latest MRP estimates?",
  "Answer Sajith Premadasa is the top candidate among poor voters based on the latest MRP estimates.",
  "Question Which candidate saw the smallest change in support among Muslims?",
  "Answer President Ranil Wickremesinghe saw the smallest change in support among Muslims.",
  "Question Who has gained the most support among better-off voters?",
  "Answer President Ranil Wickremesinghe has gained the most support among better-off voters.",
  "Question Which candidate is leading in support among voters who are unfavourable to the Aragalaya?",
  "Answer President Ranil Wickremesinghe is leading in support among voters who are unfavourable to the Aragalaya.",
  "Question Who experienced the biggest loss in support among voters with a favourable view of the Aragalaya?",
  "Answer Anura Dissanayake experienced the biggest loss in support among voters with a favourable view of the Aragalaya.",
  "Question Which candidate has the highest support increase among voters who voted for Gotabaya Rajapaksa in 2019?",
  "Answer President Ranil Wickremesinghe has the highest support increase among voters who voted for Gotabaya Rajapaksa in 2019.",
  "Question Who is the most popular candidate among Muslim voters according to the latest data?",
  "Answer Sajith Premadasa is the most popular candidate among Muslim voters according to the latest data.",
  "Question Who saw the greatest decline in support among estate/Indian Tamil voters?",
  "Answer Sajith Premadasa saw the greatest decline in support among estate/Indian Tamil voters.",
  "Question Which candidate has the highest support among voters aged 30–59 years?",
  "Answer President Ranil Wickremesinghe has the highest support among voters aged 30–59 years.",
  "Question Who is the leading candidate among voters who supported Sajith Premadasa in the 2019 Presidential Election?",
  "Answer Sajith Premadasa is the leading candidate among voters who supported him in the 2019 Presidential Election.",
  "Question Which candidate had the highest increase in support among voters aged 18–29 years?",
  "Answer Sajith Premadasa had the highest increase in support among voters aged 18–29 years.",
  "Question Who had the largest drop in support among poor voters?",
  "Answer Anura Dissanayake had the largest drop in support among poor voters.",
  "Question Who is in the second place among voters who were unfavourable to the Aragalaya?",
  "Answer Sajith Premadasa is in the second place among voters who were unfavourable to the Aragalaya.",
  "Question Which candidate has experienced the smallest increase in support among female voters?",
  "Answer Sajith Premadasa has experienced the smallest increase in support among female voters.",
  "Question Who had the largest increase in support among better-off voters?",
  "Answer President Ranil Wickremesinghe had the largest increase in support among better-off voters.",
  "Question Who is the leading candidate among voters who supported AK Dissanayake in the 2019 Presidential Election?",
  "Answer AK Dissanayake is the leading candidate among voters who supported him in the 2019 Presidential Election.",
  "Question Who has the highest support among middle-income voters?",
  "Answer President Ranil Wickremesinghe has the highest support among middle-income voters.",
  "Question Which candidate has the lowest support among voters aged 60+ years?",
  "Answer Anura Dissanayake has the lowest support among voters aged 60+ years.",
  "Question Who had the greatest support increase among voters who were previously pro-government/Rajapaksa/SLPP?",
  "Answer President Ranil Wickremesinghe had the greatest support increase among voters who were previously pro-government/Rajapaksa/SLPP.",
  "Question Who saw a decline in support among male voters?",
  "Answer Sajith Premadasa saw a decline in support among male voters.",
  "Question Which candidate has the most significant support gain among voters who did not favour the Aragalaya?",
  "Answer President Ranil Wickremesinghe has the most significant support gain among voters who did not favour the Aragalaya.",
  "Question Who had the greatest increase in support among youth (18–29 years)?",
  "Answer Sajith Premadasa had the greatest increase in support among youth (18–29 years).",
  "Question Who is in first place among better-off voters according to the August 2024 MRP model estimates?",
  "Answer President Ranil Wickremesinghe is in first place among better-off voters according to the August 2024 MRP model estimates.",
  "Question Who experienced the most significant drop in support among Sinhala voters?",
  "Answer Anura Dissanayake experienced the most significant drop in support among Sinhala voters.",
  "Question Which candidate has experienced the smallest change in support among estate/Indian Tamil voters?",
  "Answer A generic SLPP candidate has experienced the smallest change in support among estate/Indian Tamil voters.",
  "Question Who is the top candidate among voters with a favourable view of the Aragalaya?",
  "Answer Sajith Premadasa is the top candidate among voters with a favourable view of the Aragalaya.",
  "Question Who saw the highest increase in support among voters who supported Sajith Premadasa in 2019?",
  "Answer Sajith Premadasa saw the highest increase in support among voters who supported him in 2019.",
  "Question Who had the highest support among voters aged 30–59 years?",
  "Answer President Ranil Wickremesinghe had the highest support among voters aged 30–59 years.",
  "Question Which candidate has the highest drop in support among poor voters?",
  "Answer Anura Dissanayake has the highest drop in support among poor voters.",
  "Question Who had the smallest increase in support among voters aged 18–29 years?",
  "Answer President Ranil Wickremesinghe had the smallest increase in support among voters aged 18–29 years.",
  "Question Who is leading among voters who supported Gotabaya Rajapaksa in 2019?",
  "Answer President Ranil Wickremesinghe is leading among voters who supported Gotabaya Rajapaksa in 2019.",
  "Question Which candidate has the most significant support decline among Muslims?",
  "Answer A generic SLPP candidate has the most significant support decline among Muslims.",
  "Question Who is the leading candidate among voters who supported AK Dissanayake in 2019?",
  "Answer AK Dissanayake is the leading candidate among voters who supported him in the 2019 Presidential Election.",
  "Question Who experienced the largest increase in support among voters aged 60+ years?",
  "Answer President Ranil Wickremesinghe experienced the largest increase in support among voters aged 60+ years.",
  "Question Which candidate has the highest support among female voters?",
  "Answer President Ranil Wickremesinghe has the highest support among female voters.",
  "Question Who had the highest decrease in support among voters who favoured the Aragalaya?",
  "Answer Anura Dissanayake had the highest decrease in support among voters who favoured the Aragalaya.",
  "Question Who is the top candidate among voters who voted for Gotabaya Rajapaksa in 2019?",
  "Answer President Ranil Wickremesinghe is the top candidate among voters who voted for Gotabaya Rajapaksa in 2019.",
  "Question Which candidate has the lowest support among older voters (60+ years)?",
  "Answer Anura Dissanayake has the lowest support among older voters (60+ years).",
  "Question Who had the largest gain in support among better-off voters?",
  "Answer President Ranil Wickremesinghe had the largest gain in support among better-off voters.",
  "Question Who is currently the third-place candidate among voters who supported Sajith Premadasa in 2019?",
  "Answer Anura Dissanayake is currently the third-place candidate among voters who supported Sajith Premadasa in 2019.",
  "Question Which candidate had the highest increase in support among middle-income voters?",
  "Answer President Ranil Wickremesinghe had the highest increase in support among middle-income voters.",
  "Question Who is leading among voters who are unfavourable to the Aragalaya?",
  "Answer President Ranil Wickremesinghe is leading among voters who are unfavourable to the Aragalaya.",
  "Question Who saw the largest decline in support among voters who are pro-government/Rajapaksa/SLPP?",
  "Answer A generic SLPP candidate saw the largest decline in support among voters who are pro-government/Rajapaksa/SLPP.",
  "Question Which candidate experienced the greatest drop in support among Muslims?",
  "Answer Anura Dissanayake experienced the greatest drop in support among Muslims.",
  "Question Who is the leading candidate among voters aged 30–59 years?",
  "Answer President Ranil Wickremesinghe is the leading candidate among voters aged 30–59 years.",
  "Question Who had the smallest support increase among voters aged 18–29 years?",
  "Answer Sajith Premadasa had the smallest support increase among voters aged 18–29 years.",
  "Question Which candidate had the highest support among male voters?",
  "Answer President Ranil Wickremesinghe had the highest support among male voters.",
  "Question Who had the most significant support decline among poor voters?",
  "Answer Anura Dissanayake had the most significant support decline among poor voters.",
  "Question Who saw the highest support increase among voters who supported Gotabaya Rajapaksa in 2019?",
  "Answer President Ranil Wickremesinghe saw the highest support increase among voters who supported Gotabaya Rajapaksa in 2019.",
  "Question Which candidate is the top choice among voters who did not favour the Aragalaya?",
  "Answer President Ranil Wickremesinghe is the top choice among voters who did not favour the Aragalaya.",
  "Question Who had the greatest support gain among youth (18–29 years)?",
  "Answer Sajith Premadasa had the greatest support gain among youth (18–29 years).",
  "Question Which candidate is leading among voters who supported Gotabaya Rajapaksa in 2019?",
  "Answer President Ranil Wickremesinghe is leading among voters who supported Gotabaya Rajapaksa in 2019.",
  "Question Who had the largest support increase among voters with a favourable view of the Aragalaya?",
  "Answer Sajith Premadasa had the largest support increase among voters with a favourable view of the Aragalaya.",
  "Question Which candidate has the lowest support among better-off voters?",
  "Answer A generic SLPP candidate has the lowest support among better-off voters.",
  "Question Who is the top candidate among voters who are unfavourable to the Aragalaya?",
  "Answer President Ranil Wickremesinghe is the top candidate among voters who are unfavourable to the Aragalaya.",
  "Question Who saw the smallest increase in support among older voters (60+ years)?",
  "Answer Anura Dissanayake saw the smallest increase in support among older voters (60+ years).",
  "Question Who had the largest decline in support among estate/Indian Tamil voters?",
  "Answer Sajith Premadasa had the largest decline in support among estate/Indian Tamil voters.",
  "Question Which candidate has the highest support among voters who did not favour the Aragalaya?",
  "Answer President Ranil Wickremesinghe has the highest support among voters who did not favour the Aragalaya.",
  "Question Who experienced the largest gain in support among voters aged 18–29 years?",
  "Answer Sajith Premadasa experienced the largest gain in support among voters aged 18–29 years.",
  "Question Who had the highest support increase among better-off voters?",
  "Answer President Ranil Wickremesinghe had the highest support increase among better-off voters.",
  "Question Which candidate saw the most significant drop in support among Muslims?",
  "Answer Anura Dissanayake saw the most significant drop in support among Muslims.",
  "Question Who is the leading candidate among poor voters according to the August 2024 MRP model estimates?",
  "Answer Sajith Premadasa is the leading candidate among poor voters according to the August 2024 MRP model estimates.",
  "Question Who is in the second place among voters aged 30–59 years?",
  "Answer Sajith Premadasa is in the second place among voters aged 30–59 years.",
  "Question Which candidate experienced the smallest support increase among voters who were previously supportive of Rajapaksa/SLPP?",
  "Answer Anura Dissanayake experienced the smallest support increase among voters who were previously supportive of Rajapaksa/SLPP.",
  "Question Who had the highest support increase among voters aged 60+ years?",
  "Answer President Ranil Wickremesinghe had the highest support increase among voters aged 60+ years.",
  "Question Which candidate has the highest support among Muslim voters?",
  "Answer Sajith Premadasa has the highest support among Muslim voters.",
  "Question Who is the third-place candidate among voters who supported Sajith Premadasa in 2019?",
  "Answer Anura Dissanayake is the third-place candidate among voters who supported Sajith Premadasa in 2019.",
  "Question Who is the leading candidate among voters who did not favour the Aragalaya?",
  "Answer President Ranil Wickremesinghe is the leading candidate among voters who did not favour the Aragalaya.",
  "Question Which candidate had the largest increase in support among voters aged 30–59 years?",
  "Answer President Ranil Wickremesinghe had the largest increase in support among voters aged 30–59 years.",
  "Question Who saw the largest decline in support among poor voters?",
  "Answer Anura Dissanayake saw the largest decline in support among poor voters.",
  "Question Which candidate is the top choice among voters who are unfavourable to the Aragalaya?",
  "Answer President Ranil Wickremesinghe is the top choice among voters who are unfavourable to the Aragalaya.",
  "Question Who had the smallest support increase among youth (18–29 years)?",
  "Answer Sajith Premadasa had the smallest support increase among youth (18–29 years).",
  "Question Who is leading among voters who supported Gotabaya Rajapaksa in 2019?",
  "Answer President Ranil Wickremesinghe is leading among voters who supported Gotabaya Rajapaksa in 2019.",
  "Question Which candidate had the highest increase in support among better-off voters?",
  "Answer President Ranil Wickremesinghe had the highest increase in support among better-off voters.",
  "Question Who had the largest support increase among voters who were unfavourable to the Aragalaya?",
  "Answer Sajith Premadasa had the largest support increase among voters who were unfavourable to the Aragalaya.",
  "Question Which candidate has the lowest support among voters aged 18–29 years?",
  "Answer Anura Dissanayake has the lowest support among voters aged 18–29 years.",
  "Question Who is the top candidate among voters who supported AK Dissanayake in 2019?",
  "Answer AK Dissanayake is the top candidate among voters who supported him in the 2019 Presidential Election.",
  "Question Who had the most significant support gain among voters who did not favour the Aragalaya?",
  "Answer President Ranil Wickremesinghe had the most significant support gain among voters who did not favour the Aragalaya.",
  "Question Who is the leading candidate among voters aged 30–59 years?",
  "Answer President Ranil Wickremesinghe is the leading candidate among voters aged 30–59 years.",
  "Question Which candidate had the smallest increase in support among voters who were previously supportive of Rajapaksa/SLPP?",
  "Answer Anura Dissanayake had the smallest increase in support among voters who were previously supportive of Rajapaksa/SLPP.",
  "Question Who is the top candidate among voters who did not favour the Aragalaya?",
  "Answer President Ranil Wickremesinghe is the top candidate among voters who did not favour the Aragalaya.",
  "Question Who saw the highest support increase among voters aged 60+ years?",
  "Answer President Ranil Wickremesinghe saw the highest support increase among voters aged 60+ years.",
  "Question Which candidate had the largest support gain among voters who supported Gotabaya Rajapaksa in 2019?",
  "Answer President Ranil Wickremesinghe had the largest support gain among voters who supported Gotabaya Rajapaksa in 2019.",
  "Question Who had the most significant drop in support among better-off voters?",
  "Answer Anura Dissanayake had the most significant drop in support among better-off voters.",
  "Question Which candidate is the top choice among voters aged 18–29 years?",
  "Answer Sajith Premadasa is the top choice among voters aged 18–29 years.",
  "Question Who experienced the largest support gain among voters who are unfavourable to the Aragalaya?",
  "Answer President Ranil Wickremesinghe experienced the largest support gain among voters who are unfavourable to the Aragalaya.",
  "Question Who had the highest support among voters who supported Sajith Premadasa in 2019?",
  "Answer Sajith Premadasa had the highest support among voters who supported him in 2019.",
  "Question Which candidate has the most significant support decline among voters who are pro-government/Rajapaksa/SLPP?",
  "Answer Anura Dissanayake has the most significant support decline among voters who are pro-government/Rajapaksa/SLPP.",
  "Question Who had the largest increase in support among better-off voters?",
  "Answer President Ranil Wickremesinghe had the largest increase in support among better-off voters.",
  "Question Who is the leading candidate among voters who are unfavourable to the Aragalaya?",
  "Answer President Ranil Wickremesinghe is the leading candidate among voters who are unfavourable to the Aragalaya.",
  "Question Who had the most significant drop in support among poor voters?",
  "Answer Anura Dissanayake had the most significant drop in support among poor voters.",
  "Question Which candidate is the top choice among voters who did not favour the Aragalaya?",
  "Answer President Ranil Wickremesinghe is the top choice among voters who did not favour the Aragalaya.",
  "Question Who had the largest support gain among youth (18–29 years)?",
  "Answer Sajith Premadasa had the largest support gain among youth (18–29 years).",
  "Question Who had the highest support among voters aged 30–59 years?",
  "Answer President Ranil Wickremesinghe had the highest support among voters aged 30–59 years.",
  "Question Who experienced the largest drop in support among estate/Indian Tamil voters?",
  "Answer Sajith Premadasa experienced the largest drop in support among estate/Indian Tamil voters.",
  "Question Which candidate had the highest support increase among voters who are unfavourable to the Aragalaya?",
  "Answer Sajith Premadasa had the highest support increase among voters who are unfavourable to the Aragalaya.",
  "Question Who is the leading candidate among voters who supported Gotabaya Rajapaksa in 2019?",
  "Answer President Ranil Wickremesinghe is the leading candidate among voters who supported Gotabaya Rajapaksa in 2019.",
  "Question Which candidate had the highest support among voters aged 60+ years?",
  "Answer President Ranil Wickremesinghe had the highest support among voters aged 60+ years.",
  "Question Who had the most significant support decline among better-off voters?",
  "Answer Anura Dissanayake had the most significant support decline among better-off voters.",
  "Question Who is the top candidate among voters who did not favour the Aragalaya?",
  "Answer President Ranil Wickremesinghe is the top candidate among voters who did not favour the Aragalaya.",
  "Question Who had the largest support gain among voters who supported Gotabaya Rajapaksa in 2019?",
  "Answer President Ranil Wickremesinghe had the largest support gain among voters who supported Gotabaya Rajapaksa in 2019.",
  "Question Which candidate saw the smallest increase in support among voters aged 18–29 years?",
  "Answer Sajith Premadasa saw the smallest increase in support among voters aged 18–29 years.",
  "Question Who is in the second place among voters aged 30–59 years?",
  "Answer Sajith Premadasa is in the second place among voters aged 30–59 years.",
  "Question Who had the highest support among Muslim voters?",
  "Answer Sajith Premadasa had the highest support among Muslim voters.",
  "Question Which candidate experienced the largest increase in support among voters aged 18–29 years?",
  "Answer Sajith Premadasa experienced the largest increase in support among voters aged 18–29 years.",
  "Question Who had the smallest support increase among voters aged 30–59 years?",
  "Answer Anura Dissanayake had the smallest support increase among voters aged 30–59 years.",
  "Question Who is the leading candidate among voters who are unfavourable to the Aragalaya?",
  "Answer President Ranil Wickremesinghe is the leading candidate among voters who are unfavourable to the Aragalaya.",
  "Question Who had the highest support increase among voters who supported Sajith Premadasa in 2019?",
  "Answer Sajith Premadasa had the highest support increase among voters who supported him in 2019.",
  "Question Which candidate is the top choice among voters who are unfavourable to the Aragalaya?",
  "Answer President Ranil Wickremesinghe is the top choice among voters who are unfavourable to the Aragalaya.",
  "Question Who had the largest support increase among voters aged 30–59 years?",
  "Answer President Ranil Wickremesinghe had the largest support increase among voters aged 30–59 years.",
  "Question Which candidate saw the most significant drop in support among Muslims?",
  "Answer Anura Dissanayake saw the most significant drop in support among Muslims.",
  "Question Who is the leading candidate among voters who supported Gotabaya Rajapaksa in 2019?",
  "Answer President Ranil Wickremesinghe is the leading candidate among voters who supported Gotabaya Rajapaksa in 2019.",
  "Question Which candidate had the highest support among voters aged 60+ years?",
  "Answer President Ranil Wickremesinghe had the highest support among voters aged 60+ years.",
  "Question Who had the largest support gain among voters who are unfavourable to the Aragalaya?",
  "Answer Sajith Premadasa had the largest support gain among voters who are unfavourable to the Aragalaya.",
  "Question Who experienced the most significant support drop among voters who supported Gotabaya Rajapaksa in 2019?",
  "Answer Anura Dissanayake experienced the most significant support drop among voters who supported Gotabaya Rajapaksa in 2019.",
  "Question Which candidate is leading among poor voters according to the August 2024 MRP model estimates?",
  "Answer Sajith Premadasa is leading among poor voters according to the August 2024 MRP model estimates.",
  "Question Who is the top candidate among voters who did not favour the Aragalaya?",
  "Answer President Ranil Wickremesinghe is the top candidate among voters who did not favour the Aragalaya.",
  "Question Who had the smallest support increase among voters aged 60+ years?",
  "Answer Anura Dissanayake had the smallest support increase among voters aged 60+ years.",
  "Question Which candidate experienced the greatest support decline among estate/Indian Tamil voters?",
  "Answer Sajith Premadasa experienced the greatest support decline among estate/Indian Tamil voters.",
  "Question Who is leading among voters who did not favour the Aragalaya?",
  "Answer President Ranil Wickremesinghe is leading among voters who did not favour the Aragalaya.",
  "Question Which candidate saw the highest support increase among voters who are unfavourable to the Aragalaya?",
  "Answer Sajith Premadasa saw the highest support increase among voters who are unfavourable to the Aragalaya.",
  "Question Who had the largest support gain among voters who supported Gotabaya Rajapaksa in 2019?",
  "Answer President Ranil Wickremesinghe had the largest support gain among voters who supported Gotabaya Rajapaksa in 2019.",
  "Question Which candidate is the top choice among voters aged 18–29 years?",
  "Answer Sajith Premadasa is the top choice among voters aged 18–29 years.",
  "Question Who experienced the most significant support decline among better-off voters?",
  "Answer Anura Dissanayake experienced the most significant support decline among better-off voters.",
  "Question What was the overall change in support for President Ranil Wickremesinghe from January/February 2024 to June/July 2024?",
  "Answer Support for President Ranil Wickremesinghe rose significantly from 13% to 22%.",
  "Question Which demographic group showed the largest gain in support for Ranil Wickremesinghe?",
  "Answer The largest gain was among older voters, with support increasing by 24%.",
  "Question What was the percentage change in support for Anura Dissanayake across better-off voters?",
  "Answer Support for Anura Dissanayake fell by 12% among better-off voters.",
  "Question Which group did Sajith Premadasa lose the most support from?",
  "Answer Sajith Premadasa lost the most support from older adults, with a 9-point decrease.",
  "Question How did Ranil Wickremesinghe’s support change among anti-Aragalaya voters?",
  "Answer Ranil Wickremesinghe’s support increased by 26 points among anti-Aragalaya voters.",
  "Question What was the change in support for a generic SLPP candidate from January/February 2024 to June/July 2024?",
  "Answer Support for a generic SLPP candidate decreased by 5%.",
  "Question Did Ranil Wickremesinghe see a significant increase in support from Muslim voters?",
  "Answer No, Ranil Wickremesinghe did not see a significant increase in support from Muslim voters.",
  "Question How did Sajith Premadasa’s support change among youth aged 18-29?",
  "Answer Sajith Premadasa’s support increased by 12% among youth aged 18-29.",
  "Question What demographic saw a 17-point increase in support for Ranil Wickremesinghe?",
  "Answer Support for Ranil Wickremesinghe increased by 17 points among better-off voters.",
  "Question What was the support change for Anura Dissanayake among Sinhala voters?",
  "Answer Anura Dissanayake’s support among Sinhala voters fell by 9%.",
  "Question Which candidate had the largest increase in support from voters who previously supported Gotabaya Rajapakse?",
  "Answer Ranil Wickremesinghe had the largest increase in support from voters who previously supported Gotabaya Rajapakse, with a 20% rise.",
  "Question How did support for Sajith Premadasa change among poor Sri Lankans?",
  "Answer Support for Sajith Premadasa increased by 3% among poor Sri Lankans.",
  "Question What was the change in support for Anura Dissanayake among voters with a favorable view of the Aragalaya?",
  "Answer Support for Anura Dissanayake among voters with a favorable view of the Aragalaya fell by 9%.",
  "Question Which candidate saw an increase in support among women?",
  "Answer Ranil Wickremesinghe saw a 17% increase in support among women.",
  "Question How did support for a generic SLPP candidate change among older voters?",
  "Answer Support for a generic SLPP candidate fell by 13% among older voters.",
  "Question Did Sajith Premadasa gain or lose support from Muslim voters?",
  "Answer Sajith Premadasa gained 4% support from Muslim voters.",
  "Question What was the change in support for Ranil Wickremesinghe among youth aged 18-29?",
  "Answer Support for Ranil Wickremesinghe increased by 5% among youth aged 18-29.",
  "Question How did Anura Dissanayake’s support among SL Tamil voters change?",
  "Answer Support for Anura Dissanayake among SL Tamil voters increased by 5%.",
  "Question What demographic saw a 17-point increase in support for Ranil Wickremesinghe?",
  "Answer Better-off voters saw a 17-point increase in support for Ranil Wickremesinghe.",
  "Question How did Sajith Premadasa’s support change among older adults?",
  "Answer Support for Sajith Premadasa fell by 9 points among older adults.",
  "Question Which candidate experienced a decrease in support among estate/Indian Tamil voters?",
  "Answer Support for Anura Dissanayake among estate/Indian Tamil voters increased by 5%, while support for a generic SLPP candidate remained unchanged.",
  "Question What was the change in support for Ranil Wickremesinghe among anti-Aragalaya voters?",
  "Answer Ranil Wickremesinghe’s support increased by 26 points among anti-Aragalaya voters.",
  "Question How did support for Anura Dissanayake change among voters who favored the Aragalaya?",
  "Answer Support for Anura Dissanayake among voters who favored the Aragalaya fell by 9%.",
  "Question Which candidate saw an increase in support among poor Sri Lankans?",
  "Answer Sajith Premadasa saw a 3% increase in support among poor Sri Lankans.",
  "Question What was the percentage change in support for a generic SLPP candidate among poor voters?",
  "Answer Support for a generic SLPP candidate fell by 7% among poor voters.",
  "Question Which demographic showed the smallest change in support for Ranil Wickremesinghe?",
  "Answer Support for Ranil Wickremesinghe showed the smallest change among Muslim voters, remaining at 0%.",
  "Question What was the overall change in support for Sajith Premadasa from January/February 2024 to June/July 2024?",
  "Answer Support for Sajith Premadasa decreased by 1% overall.",
  "Question How did support for Anura Dissanayake among middle-income voters change?",
  "Answer Support for Anura Dissanayake among middle-income voters fell by 6%.",
  "Question Which demographic had the largest increase in support for Ranil Wickremesinghe?",
  "Answer Older voters had the largest increase in support for Ranil Wickremesinghe, with a 24-point rise.",
  "Question How did support for Sajith Premadasa among youth aged 18-29 compare to other demographics?",
  "Answer Sajith Premadasa saw the highest increase in support among youth aged 18-29, with a 12-point rise.",
  "Question What was the change in support for Ranil Wickremesinghe among better-off voters?",
  "Answer Support for Ranil Wickremesinghe increased by 17% among better-off voters.",
  "Question Which demographic saw a decrease in support for Anura Dissanayake?",
  "Answer Support for Anura Dissanayake decreased among better-off voters, Sinhala voters, and youth aged 18-29.",
  "Question How did support for Sajith Premadasa change among SL Tamil voters?",
  "Answer Support for Sajith Premadasa decreased by 5% among SL Tamil voters.",
  "Question Did Ranil Wickremesinghe experience a significant change in support among male voters?",
  "Answer Ranil Wickremesinghe saw an 8% increase in support among male voters.",
  "Question What was the support change for a generic SLPP candidate among Sinhala voters?",
  "Answer Support for a generic SLPP candidate fell by 6% among Sinhala voters.",
  "Question Which candidate had a higher gain in support from women compared to men?",
  "Answer Ranil Wickremesinghe had a higher gain in support from women (+17%) compared to men (+8%).",
  "Question How did Anura Dissanayake’s support change among estate/Indian Tamil voters?",
  "Answer Support for Anura Dissanayake increased by 5% among estate/Indian Tamil voters.",
  "Question What was the change in support for Ranil Wickremesinghe among voters who supported Gotabaya Rajapakse in 2019?",
  "Answer Support for Ranil Wickremesinghe increased by 20% among voters who supported Gotabaya Rajapakse in 2019.",
  "Question Which demographic showed a 5-point increase in support for Sajith Premadasa?",
  "Answer Support for Sajith Premadasa increased by 5 points among Muslim voters.",
  "Question How did support for a generic SLPP candidate change among younger voters?",
  "Answer Support for a generic SLPP candidate remained unchanged among younger voters aged 18-29.",
  "Question Did Ranil Wickremesinghe gain or lose support from voters with a favorable view of the Aragalaya?",
  "Answer Ranil Wickremesinghe gained 16% support from voters with a favorable view of the Aragalaya.",
  "Question How did support for Sajith Premadasa change among middle-income voters?",
  "Answer Support for Sajith Premadasa decreased by 4% among middle-income voters.",
  "Question What was the overall support change for a generic SLPP candidate among Muslim voters?",
  "Answer Support for a generic SLPP candidate remained unchanged among Muslim voters.",
  "Question How did support for Ranil Wickremesinghe change among youth aged 18-29?",
  "Answer Support for Ranil Wickremesinghe increased by 5% among youth aged 18-29.",
  "Question Which candidate had the smallest change in support among SL Tamil voters?",
  "Answer Ranil Wickremesinghe had the smallest change in support among SL Tamil voters, with a 6% increase.",
  "Question How did support for Anura Dissanayake change among poor voters?",
  "Answer Support for Anura Dissanayake fell by 4% among poor voters.",
  "Question What was the change in support for Sajith Premadasa among voters who favored the Aragalaya?",
  "Answer Support for Sajith Premadasa decreased by 3% among voters who favored the Aragalaya.",
  "Question How did support for Ranil Wickremesinghe among better-off voters compare to other groups?",
  "Answer Ranil Wickremesinghe had the highest increase in support among better-off voters, with a 17-point rise.",
  "Question Which candidate experienced the largest drop in support among voters who supported Sajith Premadasa in 2019?",
  "Answer Anura Dissanayake experienced the largest drop in support among voters who supported Sajith Premadasa in 2019.",
  "Question How did support for a generic SLPP candidate change among better-off voters?",
  "Answer Support for a generic SLPP candidate fell by 3% among better-off voters.",
  "Question Which demographic saw a decrease in support for Ranil Wickremesinghe?",
  "Answer Support for Ranil Wickremesinghe remained unchanged among Muslim voters.",
  "Question How did Sajith Premadasa’s support change among younger voters aged 18-29?",
  "Answer Sajith Premadasa’s support increased by 12% among younger voters aged 18-29.",
  "Question What was the change in support for Anura Dissanayake among voters with a negative view of the Aragalaya?",
  "Answer Support for Anura Dissanayake fell by 7% among voters with a negative view of the Aragalaya.",
  "Question Which demographic group showed the smallest increase in support for Ranil Wickremesinghe?",
  "Answer Support for Ranil Wickremesinghe showed the smallest increase among estate/Indian Tamil voters, with a 2% rise.",
  "Question How did support for Sajith Premadasa change among voters who supported Gotabaya Rajapakse in 2019?",
  "Answer Support for Sajith Premadasa decreased by 4% among voters who supported Gotabaya Rajapakse in 2019.",
  "Question Did Anura Dissanayake’s support increase or decrease among middle-income voters?",
  "Answer Anura Dissanayake’s support decreased by 6% among middle-income voters.",
  "Question How did Ranil Wickremesinghe’s support change among female voters?",
  "Answer Ranil Wickremesinghe’s support increased by 17% among female voters.",
  "Question Which candidate saw an increase in support among middle-income voters?",
  "Answer Ranil Wickremesinghe saw a 14% increase in support among middle-income voters.",
  "Question How did support for Sajith Premadasa change among estate/Indian Tamil voters?",
  "Answer Support for Sajith Premadasa decreased by 7% among estate/Indian Tamil voters.",
  "Question Which candidate experienced a decrease in support among older adults?",
  "Answer Support for a generic SLPP candidate fell by 13% among older adults.",
  "Question How did Anura Dissanayake’s support among SL Tamil voters compare to other groups?",
  "Answer Support for Anura Dissanayake increased by 5% among SL Tamil voters.",
  "Question Which demographic group saw a decrease in support for a generic SLPP candidate?",
  "Answer Support for a generic SLPP candidate decreased among older voters, with a 13-point drop.",
  "Question Did Ranil Wickremesinghe gain support among voters who favored the Aragalaya?",
  "Answer Yes, Ranil Wickremesinghe gained 16% support among voters who favored the Aragalaya.",
  "Question How did support for Sajith Premadasa change among poorer voters?",
  "Answer Support for Sajith Premadasa increased by 3% among poorer voters.",
  "Question Which candidate had the largest increase in support from female voters?",
  "Answer Ranil Wickremesinghe had the largest increase in support from female voters, with a 17% rise.",
  "Question How did support for Anura Dissanayake among better-off voters compare to other demographics?",
  "Answer Anura Dissanayake saw the largest decline in support among better-off voters, with a 12% drop.",
  "Question What was the change in support for Ranil Wickremesinghe among voters who supported Sajith Premadasa in 2019?",
  "Answer Support for Ranil Wickremesinghe increased by 8% among voters who supported Sajith Premadasa in 2019.",
  "Question How did support for Sajith Premadasa change among Muslim voters?",
  "Answer Support for Sajith Premadasa increased by 4% among Muslim voters.",
  "Question Which candidate experienced a decrease in support among youth aged 18-29?",
  "Answer Anura Dissanayake experienced a decrease in support among youth aged 18-29, with a 17-point drop.",
  "Question How did support for Ranil Wickremesinghe change among poor voters?",
  "Answer Support for Ranil Wickremesinghe increased by 8% among poor voters.",
  "Question Which demographic showed the smallest change in support for Ranil Wickremesinghe?",
  "Answer Support for Ranil Wickremesinghe showed the smallest change among Muslim voters, remaining at 0%.",
  "Question How did support for a generic SLPP candidate change among SL Tamil voters?",
  "Answer Support for a generic SLPP candidate increased by 1% among SL Tamil voters.",
  "Question Which candidate saw the smallest decrease in support among middle-income voters?",
  "Answer Support for Sajith Premadasa saw the smallest decrease among middle-income voters, with a 4% drop.",
  "Question How did support for Anura Dissanayake change among older adults?",
  "Answer Support for Anura Dissanayake decreased by 2% among older adults.",
  "Question Which candidate saw the largest increase in support among youth aged 18-29?",
  "Answer Sajith Premadasa saw the largest increase in support among youth aged 18-29, with a 12% rise.",
  "Question How did support for Ranil Wickremesinghe change among middle-income voters?",
  "Answer Support for Ranil Wickremesinghe increased by 14% among middle-income voters.",
  "Question Which demographic saw a decrease in support for Sajith Premadasa?",
  "Answer Support for Sajith Premadasa decreased among older adults, with a 9-point drop.",
  "Question How did support for a generic SLPP candidate change among voters who supported Gotabaya Rajapakse in 2019?",
  "Answer Support for a generic SLPP candidate fell by 9% among voters who supported Gotabaya Rajapakse in 2019.",
  "Question Which candidate experienced an increase in support among better-off voters?",
  "Answer Ranil Wickremesinghe experienced a 17% increase in support among better-off voters.",
  "Question How did support for Anura Dissanayake change among poor voters?",
  "Answer Support for Anura Dissanayake decreased by 4% among poor voters.",
  "Question Which candidate saw a 5-point increase in support among estate/Indian Tamil voters?",
  "Answer Support for Anura Dissanayake increased by 5 points among estate/Indian Tamil voters.",
  "Question How did Sajith Premadasa’s support change among SL Tamil voters?",
  "Answer Support for Sajith Premadasa decreased by 5% among SL Tamil voters.",
  "Question Which demographic saw a decrease in support for Ranil Wickremesinghe?",
  "Answer Support for Ranil Wickremesinghe remained unchanged among Muslim voters.",
  "Question How did support for Sajith Premadasa change among middle-income voters?",
  "Answer Support for Sajith Premadasa decreased by 4% among middle-income voters.",
  "Question Which candidate saw an increase in support from anti-Aragalaya voters?",
  "Answer Ranil Wickremesinghe saw a 26-point increase in support from anti-Aragalaya voters.",
  "Question How did support for a generic SLPP candidate change among poor voters?",
  "Answer Support for a generic SLPP candidate fell by 7% among poor voters.",
  "Question Which candidate experienced a significant increase in support from female voters?",
  "Answer Ranil Wickremesinghe experienced a significant increase in support from female voters, with a 17% rise.",
  "Question How did support for Anura Dissanayake change among middle-income voters?",
  "Answer Support for Anura Dissanayake decreased by 6% among middle-income voters.",
  "Question Which demographic saw the smallest change in support for Sajith Premadasa?",
  "Answer Support for Sajith Premadasa saw the smallest change among SL Tamil voters, with a 7% drop.",
  "Question How did support for Ranil Wickremesinghe among voters who supported Gotabaya Rajapakse in 2019 compare to other groups?",
  "Answer Support for Ranil Wickremesinghe increased by 20% among voters who supported Gotabaya Rajapakse in 2019, the largest increase among all groups.",
  "Question Which candidate saw the largest drop in support among older adults?",
  "Answer Support for a generic SLPP candidate saw the largest drop among older adults, with a 13-point decrease.",
  "Question How did support for Sajith Premadasa change among voters who supported Sajith Premadasa in 2019?",
  "Answer Support for Sajith Premadasa remained relatively stable, with only a 1% decrease among voters who supported him in 2019.",
  "Question Which candidate had the smallest increase in support from female voters?",
  "Answer Sajith Premadasa had the smallest increase in support from female voters, with a 3% rise.",
  "Question How did support for Ranil Wickremesinghe change among youth aged 18-29?",
  "Answer Support for Ranil Wickremesinghe increased by 5% among youth aged 18-29.",
  "Question Which demographic group had a 17-point increase in support for Ranil Wickremesinghe?",
  "Answer The better-off demographic group had a 17-point increase in support for Ranil Wickremesinghe.",
  "Question How did support for Anura Dissanayake change among voters with a negative view of the Aragalaya?",
  "Answer Support for Anura Dissanayake decreased by 7% among voters with a negative view of the Aragalaya.",
  "Question Which candidate experienced a 12-point increase in support among youth aged 18-29?",
  "Answer Sajith Premadasa experienced a 12-point increase in support among youth aged 18-29.",
  "Question How did support for Ranil Wickremesinghe change among middle-income voters?",
  "Answer Support for Ranil Wickremesinghe increased by 14% among middle-income voters.",
  "Question Which demographic saw a decrease in support for Sajith Premadasa?",
  "Answer Support for Sajith Premadasa decreased among older adults, with a 9-point drop.",
  "Question How did support for a generic SLPP candidate change among Sinhala voters?",
  "Answer Support for a generic SLPP candidate decreased by 6% among Sinhala voters.",
  "Question Which candidate saw a 5-point increase in support among estate/Indian Tamil voters?",
  "Answer Support for Anura Dissanayake increased by 5 points among estate/Indian Tamil voters.",
  "Question How did support for Sajith Premadasa change among Muslim voters?",
  "Answer Support for Sajith Premadasa increased by 4% among Muslim voters.",
  "Question Which candidate had the smallest increase in support from female voters?",
  "Answer Sajith Premadasa had the smallest increase in support from female voters, with a 3% rise.",
  "Question How did support for Ranil Wickremesinghe change among voters who supported Sajith Premadasa in 2019?",
  "Answer Support for Ranil Wickremesinghe increased by 8% among voters who supported Sajith Premadasa in 2019.",
  "Question Which candidate experienced the largest increase in support from female voters?",
  "Answer Ranil Wickremesinghe experienced the largest increase in support from female voters, with a 17% rise.",
  "Question How did support for Sajith Premadasa change among younger voters aged 18-29?",
  "Answer Support for Sajith Premadasa increased by 12% among younger voters aged 18-29.",
  "Question Which demographic saw the smallest change in support for Ranil Wickremesinghe?",
  "Answer Support for Ranil Wickremesinghe saw the smallest change among Muslim voters, remaining at 0%.",
  "Question How did support for a generic SLPP candidate change among voters who supported Gotabaya Rajapakse in 2019?",
  "Answer Support for a generic SLPP candidate fell by 9% among voters who supported Gotabaya Rajapakse in 2019.",
  "Question Which candidate experienced the largest drop in support among older adults?",
  "Answer Support for a generic SLPP candidate saw the largest drop among older adults, with a 13-point decrease.",
  "Question How did support for Anura Dissanayake change among SL Tamil voters?",
  "Answer Support for Anura Dissanayake increased by 5% among SL Tamil voters.",
  "Question Which demographic saw a decrease in support for Sajith Premadasa?",
  "Answer Support for Sajith Premadasa decreased among older adults, with a 9-point drop.",
  "Question How did support for Ranil Wickremesinghe change among voters with a negative view of the Aragalaya?",
  "Answer Support for Ranil Wickremesinghe increased by 16% among voters with a negative view of the Aragalaya.",
  "Question Which candidate saw an increase in support from anti-Aragalaya voters?",
  "Answer Ranil Wickremesinghe saw a 26-point increase in support from anti-Aragalaya voters.",
  "Question How did support for Anura Dissanayake change among middle-income voters?",
  "Answer Support for Anura Dissanayake decreased by 6% among middle-income voters.",
  "Question Which demographic saw the smallest increase in support for Ranil Wickremesinghe?",
  "Answer Support for Ranil Wickremesinghe saw the smallest increase among estate/Indian Tamil voters, with a 2% rise.",
  "Question How did support for Sajith Premadasa change among voters who supported Gotabaya Rajapakse in 2019?",
  "Answer Support for Sajith Premadasa decreased by 4% among voters who supported Gotabaya Rajapakse in 2019.",
  "Question Which candidate had the largest increase in support from younger voters aged 18-29?",
  "Answer Sajith Premadasa had the largest increase in support from younger voters aged 18-29, with a 12% rise.",
  "Question How did support for Ranil Wickremesinghe change among poor voters?",
  "Answer Support for Ranil Wickremesinghe increased by 8% among poor voters.",
  "Question Which demographic saw a decrease in support for Sajith Premadasa?",
  "Answer Support for Sajith Premadasa decreased among older adults, with a 9-point drop.",
  "Question How did support for a generic SLPP candidate change among voters who supported Gotabaya Rajapakse in 2019?",
  "Answer Support for a generic SLPP candidate fell by 9% among voters who supported Gotabaya Rajapakse in 2019.",
  "Question Which candidate experienced an increase in support among middle-income voters?",
  "Answer Ranil Wickremesinghe experienced a 14% increase in support among middle-income voters.",
  "Question How did support for Anura Dissanayake change among older adults?",
  "Answer Support for Anura Dissanayake decreased by 2% among older adults.",
  "Question Which candidate saw a 5-point increase in support among estate/Indian Tamil voters?",
  "Answer Support for Anura Dissanayake increased by 5 points among estate/Indian Tamil voters.",
  "Question How did Sajith Premadasa’s support change among younger voters aged 18-29?",
  "Answer Support for Sajith Premadasa increased by 12% among younger voters aged 18-29.",
  "Question Which demographic saw the smallest change in support for Ranil Wickremesinghe?",
  "Answer Support for Ranil Wickremesinghe saw the smallest change among Muslim voters, remaining at 0%.",
  "Question How did support for a generic SLPP candidate change among voters who supported Gotabaya Rajapakse in 2019?",
  "Answer Support for a generic SLPP candidate fell by 9% among voters who supported Gotabaya Rajapakse in 2019.",
  "Question Which candidate had the largest increase in support from female voters?",
  "Answer Ranil Wickremesinghe had the largest increase in support from female voters, with a 17% rise.",
  "Question How did support for Anura Dissanayake change among poor voters?",
  "Answer Support for Anura Dissanayake decreased by 4% among poor voters.",
  "Question Which candidate saw a 5-point increase in support among estate/Indian Tamil voters?",
  "Answer Support for Anura Dissanayake increased by 5 points among estate/Indian Tamil voters.",
  "Question How did support for Sajith Premadasa change among Muslim voters?",
  "Answer Support for Sajith Premadasa increased by 4% among Muslim voters.",
  "Question Which candidate experienced the smallest increase in support from female voters?",
  "Answer Sajith Premadasa experienced the smallest increase in support from female voters, with a 3% rise.",
  "Question How did support for Ranil Wickremesinghe change among voters who supported Sajith Premadasa in 2019?",
  "Answer Support for Ranil Wickremesinghe increased by 8% among voters who supported Sajith Premadasa in 2019.",
  "Question Which candidate experienced the largest drop in support among older adults?",
  "Answer Support for a generic SLPP candidate saw the largest drop among older adults, with a 13-point decrease.",
  "Question How did support for Anura Dissanayake change among SL Tamil voters?",
  "Answer Support for Anura Dissanayake increased by 5% among SL Tamil voters.",
  "Question Which demographic saw a decrease in support for Sajith Premadasa?",
  "Answer Support for Sajith Premadasa decreased among older adults, with a 9-point drop.",
  "Question How did support for Ranil Wickremesinghe change among voters with a negative view of the Aragalaya?",
  "Answer Support for Ranil Wickremesinghe increased by 16% among voters with a negative view of the Aragalaya.",
  "Question Which candidate saw an increase in support from anti-Aragalaya voters?",
  "Answer Ranil Wickremesinghe saw a 26-point increase in support from anti-Aragalaya voters.",
  "Question How did support for Anura Dissanayake change among middle-income voters?",
  "Answer Support for Anura Dissanayake decreased by 6% among middle-income voters.",
  "Question Which demographic saw the smallest increase in support for Ranil Wickremesinghe?",
  "Answer Support for Ranil Wickremesinghe saw the smallest increase among estate/Indian Tamil voters, with a 2% rise.",
  "Question How did support for Sajith Premadasa change among voters who supported Gotabaya Rajapakse in 2019?",
  "Answer Support for Sajith Premadasa decreased by 4% among voters who supported Gotabaya Rajapakse in 2019.",
  "Question Which candidate had the largest increase in support from younger voters aged 18-29?",
  "Answer Sajith Premadasa had the largest increase in support from younger voters aged 18-29, with a 12% rise.",
  "Question How did support for Ranil Wickremesinghe change among poor voters?",
  "Answer Support for Ranil Wickremesinghe increased by 8% among poor voters.",
  "Question Which demographic saw a decrease in support for Sajith Premadasa?",
  "Answer Support for Sajith Premadasa decreased among older adults, with a 9-point drop.",
  "Question How did support for a generic SLPP candidate change among voters who supported Gotabaya Rajapakse in 2019?",
  "Answer Support for a generic SLPP candidate fell by 9% among voters who supported Gotabaya Rajapakse in 2019.",
  "Question Which candidate experienced an increase in support among middle-income voters?",
  "Answer Ranil Wickremesinghe experienced a 14% increase in support among middle-income voters.",
  "Question How did support for Anura Dissanayake change among older adults?",
  "Answer Support for Anura Dissanayake decreased by 2% among older adults.",
  "Question Which candidate saw a 5-point increase in support among estate/Indian Tamil voters?",
  "Answer Support for Anura Dissanayake increased by 5 points among estate/Indian Tamil voters.",
  "Question How did Sajith Premadasa’s support change among younger voters aged 18-29?",
  "Answer Support for Sajith Premadasa increased by 12% among younger voters aged 18-29.",
  "Question Which demographic saw the smallest change in support for Ranil Wickremesinghe?",
  "Answer Support for Ranil Wickremesinghe saw the smallest change among Muslim voters, remaining at 0%.",
  "Question How did support for a generic SLPP candidate change among voters who supported Gotabaya Rajapakse in 2019?",
  "Answer Support for a generic SLPP candidate fell by 9% among voters who supported Gotabaya Rajapakse in 2019.",
  "Question Which candidate had the largest increase in support from female voters?",
  "Answer Ranil Wickremesinghe had the largest increase in support from female voters, with a 17% rise.",
  "Question How did support for Anura Dissanayake change among poor voters?",
  "Answer Support for Anura Dissanayake decreased by 4% among poor voters.",
  "Question Which candidate saw a 5-point increase in support among estate/Indian Tamil voters?",
  "Answer Support for Anura Dissanayake increased by 5 points among estate/Indian Tamil voters.",
  "Question How did support for Sajith Premadasa change among Muslim voters?",
  "Answer Support for Sajith Premadasa increased by 4% among Muslim voters.",
  "Question Which candidate experienced the smallest increase in support from female voters?",
  "Answer Sajith Premadasa experienced the smallest increase in support from female voters, with a 3% rise.",
  "Question How did support for Ranil Wickremesinghe change among voters who supported Sajith Premadasa in 2019?",
  "Answer Support for Ranil Wickremesinghe increased by 8% among voters who supported Sajith Premadasa in 2019.",
  "Question Which candidate experienced the largest drop in support among older adults?",
  "Answer Support for a generic SLPP candidate saw the largest drop among older adults, with a 13-point decrease.",
  "Question How did support for Anura Dissanayake change among SL Tamil voters?",
  "Answer Support for Anura Dissanayake increased by 5% among SL Tamil voters.",
  "Question Which demographic saw a decrease in support for Sajith Premadasa?",
  "Answer Support for Sajith Premadasa decreased among older adults, with a 9-point drop.",
  "Question How did support for Ranil Wickremesinghe change among voters with a negative view of the Aragalaya?",
  "Answer Support for Ranil Wickremesinghe increased by 16% among voters with a negative view of the Aragalaya.",
  "Question Which candidate saw an increase in support from anti-Aragalaya voters?",
  "Answer Ranil Wickremesinghe saw a 26-point increase in support from anti-Aragalaya voters.",
  "Question How did support for Anura Dissanayake change among middle-income voters?",
  "Answer Support for Anura Dissanayake decreased by 6% among middle-income voters.",
  "Question Which demographic saw the smallest increase in support for Ranil Wickremesinghe?",
  "Answer Support for Ranil Wickremesinghe saw the smallest increase among estate/Indian Tamil voters, with a 2% rise.",
  "Question How did support for Sajith Premadasa change among voters who supported Gotabaya Rajapakse in 2019?",
  "Answer Support for Sajith Premadasa decreased by 4% among voters who supported Gotabaya Rajapakse in 2019.",
  "Question Which candidate had the largest increase in support from younger voters aged 18-29?",
  "Answer Sajith Premadasa had the largest increase in support from younger voters aged 18-29, with a 12% rise.",
  "Question How did support for Ranil Wickremesinghe change among poor voters?",
  "Answer Support for Ranil Wickremesinghe increased by 8% among poor voters.",
  "Question Which demographic saw a decrease in support for Sajith Premadasa?",
  "Answer Support for Sajith Premadasa decreased among older adults, with a 9-point drop.",
  "Question How did support for a generic SLPP candidate change among voters who supported Gotabaya Rajapakse in 2019?",
  "Answer Support for a generic SLPP candidate fell by 9% among voters who supported Gotabaya Rajapakse in 2019.",
  "Question Which candidate experienced an increase in support among middle-income voters?",
  "Answer Ranil Wickremesinghe experienced a 14% increase in support among middle-income voters.",
  "Question How did support for Anura Dissanayake change among older adults?",
  "Answer Support for Anura Dissanayake decreased by 2% among older adults.",
  "Question Which candidate saw a 5-point increase in support among estate/Indian Tamil voters?",
  "Answer Support for Anura Dissanayake increased by 5 points among estate/Indian Tamil voters.",
  "Question How did Sajith Premadasa’s support change among younger voters aged 18-29?",
  "Answer Support for Sajith Premadasa increased by 12% among younger voters aged 18-29.",
  "Question Which demographic saw the smallest change in support for Ranil Wickremesinghe?",
  "Answer Support for Ranil Wickremesinghe saw the smallest change among Muslim voters, remaining at 0%.",
  "Question How did support for a generic SLPP candidate change among voters who supported Gotabaya Rajapakse in 2019?",
  "Answer Support for a generic SLPP candidate fell by 9% among voters who supported Gotabaya Rajapakse in 2019.",
  "Question Which candidate had the largest increase in support from female voters?",
  "Answer Ranil Wickremesinghe had the largest increase in support from female voters, with a 17% rise.",
  "Question How did support for Anura Dissanayake change among poor voters?",
  "Answer Support for Anura Dissanayake decreased by 4% among poor voters.",
  "Question Which candidate saw a 5-point increase in support among estate/Indian Tamil voters?",
  "Answer Support for Anura Dissanayake increased by 5 points among estate/Indian Tamil voters.",
  "Question How did support for Sajith Premadasa change among Muslim voters?",
  "Answer Support for Sajith Premadasa increased by 4% among Muslim voters.",
  "Question Which candidate experienced the smallest increase in support from female voters?",
  "Answer Sajith Premadasa experienced the smallest increase in support from female voters, with a 3% rise.",
  "Question How did support for Ranil Wickremesinghe change among voters who supported Sajith Premadasa in 2019?",
  "Answer Support for Ranil Wickremesinghe increased by 8% among voters who supported Sajith Premadasa in 2019.",
  "Question Which candidate experienced the largest drop in support among older adults?",
  "Answer Support for a generic SLPP candidate saw the largest drop among older adults, with a 13-point decrease.",
  "Question How did support for Anura Dissanayake change among SL Tamil voters?",
  "Answer Support for Anura Dissanayake increased by 5% among SL Tamil voters.",
  "Question Which demographic saw a decrease in support for Sajith Premadasa?",
  "Answer Support for Sajith Premadasa decreased among older adults, with a 9-point drop.",
  "Question How did support for Ranil Wickremesinghe change among voters with a negative view of the Aragalaya?",
  "Answer Support for Ranil Wickremesinghe increased by 16% among voters with a negative view of the Aragalaya.",
  "Question Which candidate saw an increase in support from anti-Aragalaya voters?",
  "Answer Ranil Wickremesinghe saw a 26-point increase in support from anti-Aragalaya voters.",
  "Question How did support for Anura Dissanayake change among middle-income voters?",
  "Answer Support for Anura Dissanayake decreased by 6% among middle-income voters.",
  "Question Which demographic saw the smallest increase in support for Ranil Wickremesinghe?",
  "Answer Support for Ranil Wickremesinghe saw the smallest increase among estate/Indian Tamil voters, with a 2% rise.",
  "Question How did support for Sajith Premadasa change among voters who supported Gotabaya Rajapakse in 2019?",
  "Answer Support for Sajith Premadasa decreased by 4% among voters who supported Gotabaya Rajapakse in 2019.",
  "Question Which candidate had the largest increase in support from younger voters aged 18-29?",
  "Answer Sajith Premadasa had the largest increase in support from younger voters aged 18-29, with a 12% rise.",
  "Question How did support for Ranil Wickremesinghe change among poor voters?",
  "Answer Support for Ranil Wickremesinghe increased by 8% among poor voters.",
  "Question Which demographic saw a decrease in support for Sajith Premadasa?",
  "Answer Support for Sajith Premadasa decreased among older adults, with a 9-point drop.",
  "Question How did support for a generic SLPP candidate change among voters who supported Gotabaya Rajapakse in 2019?",
  "Answer Support for a generic SLPP candidate fell by 9% among voters who supported Gotabaya Rajapakse in 2019.",
  "Question Which candidate experienced an increase in support among middle-income voters?",
  "Answer Ranil Wickremesinghe experienced a 14% increase in support among middle-income voters.",
  "Question How did support for Anura Dissanayake change among older adults?",
  "Answer Support for Anura Dissanayake decreased by 2% among older adults.",
  "Question Which candidate saw a 5-point increase in support among estate/Indian Tamil voters?",
  "Answer Support for Anura Dissanayake increased by 5 points among estate/Indian Tamil voters.",
  "Question How did Sajith Premadasa’s support change among younger voters aged 18-29?",
  "Answer Support for Sajith Premadasa increased by 12% among younger voters aged 18-29.",
  "Question Which demographic saw the smallest change in support for Ranil Wickremesinghe?",
  "Answer Support for Ranil Wickremesinghe saw the smallest change among Muslim voters, remaining at 0%.",
  "Question How did support for a generic SLPP candidate change among voters who supported Gotabaya Rajapakse in 2019?",
  "Answer Support for a generic SLPP candidate fell by 9% among voters who supported Gotabaya Rajapakse in 2019.",
  "Question Which candidate had the largest increase in support from female voters?",
  "Answer Ranil Wickremesinghe had the largest increase in support from female voters, with a 17% rise.",
  "Question How did support for Anura Dissanayake change among poor voters?",
  "Answer Support for Anura Dissanayake decreased by 4% among poor voters.",
  "Question Which candidate saw a 5-point increase in support among estate/Indian Tamil voters?",
  "Answer Support for Anura Dissanayake increased by 5 points among estate/Indian Tamil voters.",
  "Question How did support for Sajith Premadasa change among Muslim voters?",
  "Answer Support for Sajith Premadasa increased by 4% among Muslim voters.",
  "Question Which candidate experienced the smallest increase in support from female voters?",
  "Answer Sajith Premadasa experienced the smallest increase in support from female voters, with a 3% rise.",
  "Question How did support for Ranil Wickremesinghe change among voters who supported Sajith Premadasa in 2019?",
  "Answer Support for Ranil Wickremesinghe increased by 8% among voters who supported Sajith Premadasa in 2019.",
  "Question Which candidate experienced the largest drop in support among older adults?",
  "Answer Support for a generic SLPP candidate saw the largest drop among older adults, with a 13-point decrease.",
  "Question How did support for Anura Dissanayake change among SL Tamil voters?",
  "Answer Support for Anura Dissanayake increased by 5% among SL Tamil voters.",
  "Question Which demographic saw a decrease in support for Sajith Premadasa?",
  "Answer Support for Sajith Premadasa decreased among older adults, with a 9-point drop.",
  "Question How did support for Ranil Wickremesinghe change among voters with a negative view of the Aragalaya?",
  "Answer Support for Ranil Wickremesinghe increased by 16% among voters with a negative view of the Aragalaya.",
  "Question Which candidate saw an increase in support from anti-Aragalaya voters?",
  "Answer Ranil Wickremesinghe saw a 26-point increase in support from anti-Aragalaya voters.",
  "Question How did support for Anura Dissanayake change among middle-income voters?",
  "Answer Support for Anura Dissanayake decreased by 6% among middle-income voters.",
  "Question Which demographic saw the smallest increase in support for Ranil Wickremesinghe?",
  "Answer Support for Ranil Wickremesinghe saw the smallest increase among estate/Indian Tamil voters, with a 2% rise.",
  "Question How did support for Sajith Premadasa change among voters who supported Gotabaya Rajapakse in 2019?",
  "Answer Support for Sajith Premadasa decreased by 4% among voters who supported Gotabaya Rajapakse in 2019.",
  "Question Which candidate had the largest increase in support from younger voters aged 18-29?",
  "Answer Sajith Premadasa had the largest increase in support from younger voters aged 18-29, with a 12% rise.",
  "Question How did support for Ranil Wickremesinghe change among poor voters?",
  "Answer Support for Ranil Wickremesinghe increased by 8% among poor voters.",
  "Question Which demographic saw a decrease in support for Sajith Premadasa?",
  "Answer Support for Sajith Premadasa decreased among older adults, with a 9-point drop.",
  "Question How did support for a generic SLPP candidate change among voters who supported Gotabaya Rajapakse in 2019?",
  "Answer Support for a generic SLPP candidate fell by 9% among voters who supported Gotabaya Rajapakse in 2019.",
  "Question Which candidate experienced an increase in support among middle-income voters?",
  "Answer Ranil Wickremesinghe experienced a 14% increase in support among middle-income voters.",
  "Question How did support for Anura Dissanayake change among older adults?",
  "Answer Support for Anura Dissanayake decreased by 2% among older adults.",
  "Question Which candidate saw a 5-point increase in support among estate/Indian Tamil voters?",
  "Answer Support for Anura Dissanayake increased by 5 points among estate/Indian Tamil voters.",
  "Question How did Sajith Premadasa’s support change among younger voters aged 18-29?",
  "Answer Support for Sajith Premadasa increased by 12% among younger voters aged 18-29.",
  "Question Which demographic saw the smallest change in support for Ranil Wickremesinghe?",
  "Answer Support for Ranil Wickremesinghe saw the smallest change among Muslim voters, remaining at 0%.",
  "Question How did support for a generic SLPP candidate change among voters who supported Gotabaya Rajapakse in 2019?",
  "Answer Support for a generic SLPP candidate fell by 9% among voters who supported Gotabaya Rajapakse in 2019.",
  "Question Which candidate had the largest increase in support from female voters?",
  "Answer Ranil Wickremesinghe had the largest increase in support from female voters, with a 17% rise.",
  "Question How did support for Anura Dissanayake change among poor voters?",
  "Answer Support for Anura Dissanayake decreased by 4% among poor voters.",
  "Question Which candidate saw a 5-point increase in support among estate/Indian Tamil voters?",
  "Answer Support for Anura Dissanayake increased by 5 points among estate/Indian Tamil voters.",
  "Question How did support for Sajith Premadasa change among Muslim voters?",
  "Answer Support for Sajith Premadasa increased by 4% among Muslim voters.",
  "Question Which candidate experienced the smallest increase in support from female voters?",
  "Answer Sajith Premadasa experienced the smallest increase in support from female voters, with a 3% rise.",
  "Question How did support for Ranil Wickremesinghe change among voters who supported Sajith Premadasa in 2019?",
  "Answer Support for Ranil Wickremesinghe increased by 8% among voters who supported Sajith Premadasa in 2019.",
  "Question Which candidate experienced the largest drop in support among older adults?",
  "Answer Support for a generic SLPP candidate saw the largest drop among older adults, with a 13-point decrease.",
  "Question How did support for Anura Dissanayake change among SL Tamil voters?",
  "Answer Support for Anura Dissanayake increased by 5% among SL Tamil voters.",
  "Question Which demographic saw a decrease in support for Sajith Premadasa?",
  "Answer Support for Sajith Premadasa decreased among older adults, with a 9-point drop.",
  "Question How did support for Ranil Wickremesinghe change among voters with a negative view of the Aragalaya?",
  "Answer Support for Ranil Wickremesinghe increased by 16% among voters with a negative view of the Aragalaya.",
  "Question Which candidate saw an increase in support from anti-Aragalaya voters?",
  "Answer Ranil Wickremesinghe saw a 26-point increase in support from anti-Aragalaya voters.",
  "Question How did support for Anura Dissanayake change among middle-income voters?",
  "Answer Support for Anura Dissanayake decreased by 6% among middle-income voters.",
  "Question Which demographic saw the smallest increase in support for Ranil Wickremesinghe?",
  "Answer Support for Ranil Wickremesinghe saw the smallest increase among estate/Indian Tamil voters, with a 2% rise.",
  "Question How did support for Sajith Premadasa change among voters who supported Gotabaya Rajapakse in 2019?",
  "Answer Support for Sajith Premadasa decreased by 4% among voters who supported Gotabaya Rajapakse in 2019.",
  "Question Which candidate had the largest increase in support from younger voters aged 18-29?",
  "Answer Sajith Premadasa had the largest increase in support from younger voters aged 18-29, with a 12% rise.",
  "Question How did support for Ranil Wickremesinghe change among poor voters?",
  "Answer Support for Ranil Wickremesinghe increased by 8% among poor voters.",
  "Question Which demographic saw a decrease in support for Sajith Premadasa?",
  "Answer Support for Sajith Premadasa decreased among older adults, with a 9-point drop.",
  "Question How did support for a generic SLPP candidate change among voters who supported Gotabaya Rajapakse in 2019?",
  "Answer Support for a generic SLPP candidate fell by 9% among voters who supported Gotabaya Rajapakse in 2019.",
  "Question Which candidate experienced an increase in support among middle-income voters?",
  "Answer Ranil Wickremesinghe experienced a 14% increase in support among middle-income voters.",
  "Question How did support for Anura Dissanayake change among older adults?",
  "Answer Support for Anura Dissanayake decreased by 2% among older adults.",
  "Question Which candidate saw a 5-point increase in support among estate/Indian Tamil voters?",
  "Answer Support for Anura Dissanayake increased by 5 points among estate/Indian Tamil voters.",
  "Question How did Sajith Premadasa’s support change among younger voters aged 18-29?",
  "Answer Support for Sajith Premadasa increased by 12% among younger voters aged 18-29.",
  "Question Which demographic saw the smallest change in support for Ranil Wickremesinghe?",
  "Answer Support for Ranil Wickremesinghe saw the smallest change among Muslim voters, remaining at 0%.",
  "Question How did support for a generic SLPP candidate change among voters who supported Gotabaya Rajapakse in 2019?",
  "Answer Support for a generic SLPP candidate fell by 9% among voters who supported Gotabaya Rajapakse in 2019.",
  "Question Which candidate had the largest increase in support from female voters?",
  "Answer Ranil Wickremesinghe had the largest increase in support from female voters, with a 17% rise.",
  "Question How did support for Anura Dissanayake change among poor voters?",
  "Answer Support for Anura Dissanayake decreased by 4% among poor voters.",
  "Question Which candidate saw a 5-point increase in support among estate/Indian Tamil voters?",
  "Answer Support for Anura Dissanayake increased by 5 points among estate/Indian Tamil voters.",
  "Question How did support for Sajith Premadasa change among Muslim voters?",
  "Answer Support for Sajith Premadasa increased by 4% among Muslim voters.",
  "Question Which candidate experienced the smallest increase in support from female voters?",
  "Answer Sajith Premadasa experienced the smallest increase in support from female voters, with a 3% rise.",
  "Question How did support for Ranil Wickremesinghe change among voters who supported Sajith Premadasa in 2019?",
  "Answer Support for Ranil Wickremesinghe increased by 8% among voters who supported Sajith Premadasa in 2019.",
  "Question Which candidate experienced the largest drop in support among older adults?",
  "Answer Support for a generic SLPP candidate saw the largest drop among older adults, with a 13-point decrease.",
  "Question How did support for Anura Dissanayake change among SL Tamil voters?",
  "Answer Support for Anura Dissanayake increased by 5% among SL Tamil voters.",
  "Question Which demographic saw a decrease in support for Sajith Premadasa?",
  "Answer Support for Sajith Premadasa decreased among older adults, with a 9-point drop.",
  "Question How did support for Ranil Wickremesinghe change among voters with a negative view of the Aragalaya?",
  "Answer Support for Ranil Wickremesinghe increased by 16% among voters with a negative view of the Aragalaya.",
  "Question Which candidate saw an increase in support from anti-Aragalaya voters?",
  "Answer Ranil Wickremesinghe saw a 26-point increase in support from anti-Aragalaya voters.",
  "Question How did support for Anura Dissanayake change among middle-income voters?",
  "Answer Support for Anura Dissanayake decreased by 6% among middle-income voters.",
  "Question Which demographic saw the smallest increase in support for Ranil Wickremesinghe?",
  "Answer Support for Ranil Wickremesinghe saw the smallest increase among estate/Indian Tamil voters, with a 2% rise.",
  "Question How did support for Sajith Premadasa change among voters who supported Gotabaya Rajapakse in 2019?",
  "Answer Support for Sajith Premadasa decreased by 4% among voters who supported Gotabaya Rajapakse in 2019.",
  "Question Which candidate had the largest increase in support from younger voters aged 18-29?",
  "Answer Sajith Premadasa had the largest increase in support from younger voters aged 18-29, with a 12% rise.",
  "Question How did support for Ranil Wickremesinghe change among poor voters?",
  "Answer Support for Ranil Wickremesinghe increased by 8% among poor voters.",
  "Question Which demographic saw a decrease in support for Sajith Premadasa?",
  "Answer Support for Sajith Premadasa decreased among older adults, with a 9-point drop.",
  "Question How did support for a generic SLPP candidate change among voters who supported Gotabaya Rajapakse in 2019?",
  "Answer Support for a generic SLPP candidate fell by 9% among voters who supported Gotabaya Rajapakse in 2019.",
  "Question Which candidate experienced an increase in support among middle-income voters?",
  "Answer Ranil Wickremesinghe experienced a 14% increase in support among middle-income voters.",
  "Question How did support for Anura Dissanayake change among older adults?",
  "Answer Support for Anura Dissanayake decreased by 2% among older adults.",
  "Question Which candidate saw a 5-point increase in support among estate/Indian Tamil voters?",
  "Answer Support for Anura Dissanayake increased by 5 points among estate/Indian Tamil voters.",
  "Question How did Sajith Premadasa’s support change among younger voters aged 18-29?",
  "Answer Support for Sajith Premadasa increased by 12% among younger voters aged 18-29.",
  "Question Which demographic saw the smallest change in support for Ranil Wickremesinghe?",
  "Answer Support for Ranil Wickremesinghe saw the smallest change among Muslim voters, remaining at 0%.",
  "Question How did support for a generic SLPP candidate change among voters who supported Gotabaya Rajapakse in 2019?",
  "Answer Support for a generic SLPP candidate fell by 9% among voters who supported Gotabaya Rajapakse in 2019.",
  "Question Which candidate had the largest increase in support from female voters?",
  "Answer Ranil Wickremesinghe had the largest increase in support from female voters, with a 17% rise.",
  "Question How did support for Anura Dissanayake change among poor voters?",
  "Answer Support for Anura Dissanayake decreased by 4% among poor voters.",
  "Question Which candidate saw a 5-point increase in support among estate/Indian Tamil voters?",
  "Answer Support for Anura Dissanayake increased by 5 points among estate/Indian Tamil voters.",
  "Question How did support for Sajith Premadasa change among Muslim voters?",
  "Answer Support for Sajith Premadasa increased by 4% among Muslim voters.",
  "Question Which candidate experienced the smallest increase in support from female voters?",
  "Answer Sajith Premadasa experienced the smallest increase in support from female voters, with a 3% rise.",
  "Question How did support for Ranil Wickremesinghe change among voters who supported Sajith Premadasa in 2019?",
  "Answer Support for Ranil Wickremesinghe increased by 8% among voters who supported Sajith Premadasa in 2019.",
  "Question Which candidate experienced the largest drop in support among older adults?",
  "Answer Support for a generic SLPP candidate saw the largest drop among older adults, with a 13-point decrease.",
  "Question How did support for Anura Dissanayake change among SL Tamil voters?",
  "Answer Support for Anura Dissanayake increased by 5% among SL Tamil voters.",
  "Question Which demographic saw a decrease in support for Sajith Premadasa?",
  "Answer Support for Sajith Premadasa decreased among older adults, with a 9-point drop.",
  "Question How did support for Ranil Wickremesinghe change among voters with a negative view of the Aragalaya?",
  "Answer Support for Ranil Wickremesinghe increased by 16% among voters with a negative view of the Aragalaya.",
  "Question Which candidate saw an increase in support from anti-Aragalaya voters?",
  "Answer Ranil Wickremesinghe saw a 26-point increase in support from anti-Aragalaya voters.",
  "Question How did support for Anura Dissanayake change among middle-income voters?",
  "Answer Support for Anura Dissanayake decreased by 6% among middle-income voters.",
  "Question Which demographic saw the smallest increase in support for Ranil Wickremesinghe?",
  "Answer Support for Ranil Wickremesinghe saw the smallest increase among estate/Indian Tamil voters, with a 2% rise.",
  "Question How did support for Sajith Premadasa change among voters who supported Gotabaya Rajapakse in 2019?",
  "Answer Support for Sajith Premadasa decreased by 4% among voters who supported Gotabaya Rajapakse in 2019.",
  "Question Which candidate had the largest increase in support from younger voters aged 18-29?",
  "Answer Sajith Premadasa had the largest increase in support from younger voters aged 18-29, with a 12% rise.",
  "Question How did support for Ranil Wickremesinghe change among poor voters?",
  "Answer Support for Ranil Wickremesinghe increased by 8% among poor voters.",
  "Question Which demographic saw a decrease in support for Sajith Premadasa?",
  "Answer Support for Sajith Premadasa decreased among older adults, with a 9-point drop.",
  "Question How did support for a generic SLPP candidate change among voters who supported Gotabaya Rajapakse in 2019?",
  "Answer Support for a generic SLPP candidate fell by 9% among voters who supported Gotabaya Rajapakse in 2019.",
  "Question Which candidate experienced an increase in support among middle-income voters?",
  "Answer Ranil Wickremesinghe experienced a 14% increase in support among middle-income voters.",
  "Question How did support for Anura Dissanayake change among older adults?",
  "Answer Support for Anura Dissanayake decreased by 2% among older adults.",
  "Question Which candidate saw a 5-point increase in support among estate/Indian Tamil voters?",
  "Answer Support for Anura Dissanayake increased by 5 points among estate/Indian Tamil voters.",
  "Question How did Sajith Premadasa’s support change among younger voters aged 18-29?",
  "Answer Support for Sajith Premadasa increased by 12% among younger voters aged 18-29.",
  "Question Which demographic saw the smallest change in support for Ranil Wickremesinghe?",
  "Answer Support for Ranil Wickremesinghe saw the smallest change among Muslim voters, remaining at 0%.",
  "Question How did support for a generic SLPP candidate change among voters who supported Gotabaya Rajapakse in 2019?",
  "Answer Support for a generic SLPP candidate fell by 9% among voters who supported Gotabaya Rajapakse in 2019.",
  "Question Which candidate had the largest increase in support from female voters?",
  "Answer Ranil Wickremesinghe had the largest increase in support from female voters, with a 17% rise.",
  "Question How did support for Anura Dissanayake change among poor voters?",
  "Answer Support for Anura Dissanayake decreased by 4% among poor voters.",
  "Question Which candidate saw a 5-point increase in support among estate/Indian Tamil voters?",
  "Answer Support for Anura Dissanayake increased by 5 points among estate/Indian Tamil voters.",
  "Question How did support for Sajith Premadasa change among Muslim voters?",
  "Answer Support for Sajith Premadasa increased by 4% among Muslim voters.",
  "Question Which candidate experienced the smallest increase in support from female voters?",
  "Answer Sajith Premadasa experienced the smallest increase in support from female voters, with a 3% rise.",
  "Question How did support for Ranil Wickremesinghe change among voters who supported Sajith Premadasa in 2019?",
  "Answer Support for Ranil Wickremesinghe increased by 8% among voters who supported Sajith Premadasa in 2019.",
  "Question Which candidate experienced the largest drop in support among older adults?",
  "Answer Support for a generic SLPP candidate saw the largest drop among older adults, with a 13-point decrease.",
  "Question How did support for Anura Dissanayake change among SL Tamil voters?",
  "Answer Support for Anura Dissanayake increased by 5% among SL Tamil voters.",
  "Question Which demographic saw a decrease in support for Sajith Premadasa?",
  "Answer Support for Sajith Premadasa decreased among older adults, with a 9-point drop.",
  "Question How did support for Ranil Wickremesinghe change among voters with a negative view of the Aragalaya?",
  "Answer Support for Ranil Wickremesinghe increased by 16% among voters with a negative view of the Aragalaya.",
  "Question Which candidate saw an increase in support from anti-Aragalaya voters?",
  "Answer Ranil Wickremesinghe saw a 26-point increase in support from anti-Aragalaya voters.",
  "Question How did support for Anura Dissanayake change among middle-income voters?",
  "Answer Support for Anura Dissanayake decreased by 6% among middle-income voters.",
  "Question Which demographic saw the smallest increase in support for Ranil Wickremesinghe?",
  "Answer Support for Ranil Wickremesinghe saw the smallest increase among estate/Indian Tamil voters, with a 2% rise.",
  "Question How did support for Sajith Premadasa change among voters who supported Gotabaya Rajapakse in 2019?",
  "Answer Support for Sajith Premadasa decreased by 4% among voters who supported Gotabaya Rajapakse in 2019.",
  "Question Which candidate had the largest increase in support from younger voters aged 18-29?",
  "Answer Sajith Premadasa had the largest increase in support from younger voters aged 18-29, with a 12% rise.",
  "Question How did support for Ranil Wickremesinghe change among poor voters?",
  "Answer Support for Ranil Wickremesinghe increased by 8% among poor voters.",
  "Question Which demographic saw a decrease in support for Sajith Premadasa?",
  "Answer Support for Sajith Premadasa decreased among older adults, with a 9-point drop.",
  "Question How did support for a generic SLPP candidate change among voters who supported Gotabaya Rajapakse in 2019?",
  "Answer Support for a generic SLPP candidate fell by 9% among voters who supported Gotabaya Rajapakse in 2019.",
  "Question Which candidate experienced an increase in support among middle-income voters?",
  "Answer Ranil Wickremesinghe experienced a 14% increase in support among middle-income voters.",
  "Question How did support for Anura Dissanayake change among older adults?",
  "Answer Support for Anura Dissanayake decreased by 2% among older adults.",
  "Question Which candidate saw a 5-point increase in support among estate/Indian Tamil voters?",
  "Answer Support for Anura Dissanayake increased by 5 points among estate/Indian Tamil voters.",
  "Question How did Sajith Premadasa’s support change among younger voters aged 18-29?",
  "Answer Support for Sajith Premadasa increased by 12% among younger voters aged 18-29.",
  "Question Which demographic saw the smallest change in support for Ranil Wickremesinghe?",
  "Answer Support for Ranil Wickremesinghe saw the smallest change among Muslim voters, remaining at 0%.",
  "Question How did support for a generic SLPP candidate change among voters who supported Gotabaya Rajapakse in 2019?",
  "Answer Support for a generic SLPP candidate fell by 9% among voters who supported Gotabaya Rajapakse in 2019.",
  "Question Which candidate had the largest increase in support from female voters?",
  "Answer Ranil Wickremesinghe had the largest increase in support from female voters, with a 17% rise.",
  "Question How did support for Anura Dissanayake change among poor voters?",
  "Answer Support for Anura Dissanayake decreased by 4% among poor voters.",
  "Question Which candidate saw a 5-point increase in support among estate/Indian Tamil voters?",
  "Answer Support for Anura Dissanayake increased by 5 points among estate/Indian Tamil voters.",
  "Question How did support for Sajith Premadasa change among Muslim voters?",
  "Answer Support for Sajith Premadasa increased by 4% among Muslim voters.",
  "Question Which candidate experienced the smallest increase in support from female voters?",
  "Answer Sajith Premadasa experienced the smallest increase in support from female voters, with a 3% rise.",
  "Question How did support for Ranil Wickremesinghe change among voters who supported Sajith Premadasa in 2019?",
  "Answer Support for Ranil Wickremesinghe increased by 8% among voters who supported Sajith Premadasa in 2019.",
  "Question Which candidate experienced the largest drop in support among older adults?",
  "Answer Support for a generic SLPP candidate saw the largest drop among older adults, with a 13-point decrease.",
  "Question How did support for Anura Dissanayake change among SL Tamil voters?",
  "Answer Support for Anura Dissanayake increased by 5% among SL Tamil voters.",
  "Question Which demographic saw a decrease in support for Sajith Premadasa?",
  "Answer Support for Sajith Premadasa decreased among older adults, with a 9-point drop.",
  "Question How did support for Ranil Wickremesinghe change among voters with a negative view of the Aragalaya?",
  "Answer Support for Ranil Wickremesinghe increased by 16% among voters with a negative view of the Aragalaya.",
  "Question Which candidate saw an increase in support from anti-Aragalaya voters?",
  "Answer Ranil Wickremesinghe saw a 26-point increase in support from anti-Aragalaya voters.",
  "Question How did support for Anura Dissanayake change among middle-income voters?",
  "Answer Support for Anura Dissanayake decreased by 6% among middle-income voters.",
  "Question Which demographic saw the smallest increase in support for Ranil Wickremesinghe?",
  "Answer Support for Ranil Wickremesinghe saw the smallest increase among estate/Indian Tamil voters, with a 2% rise.",
  "Question How did support for Sajith Premadasa change among voters who supported Gotabaya Rajapakse in 2019?",
  "Answer Support for Sajith Premadasa decreased by 4% among voters who supported Gotabaya Rajapakse in 2019.",
  "Question Which candidate had the largest increase in support from younger voters aged 18-29?",
  "Answer Sajith Premadasa had the largest increase in support from younger voters aged 18-29, with a 12% rise.",
  "Question How did support for Ranil Wickremesinghe change among poor voters?",
  "Answer Support for Ranil Wickremesinghe increased by 8% among poor voters.",
  "Question Which demographic saw a decrease in support for Sajith Premadasa?",
  "Answer Support for Sajith Premadasa decreased among older adults, with a 9-point drop.",
  "Question How did support for a generic SLPP candidate change among voters who supported Gotabaya Rajapakse in 2019?",
  "Answer Support for a generic SLPP candidate fell by 9% among voters who supported Gotabaya Rajapakse in 2019.",
  "Question Which candidate experienced an increase in support among middle-income voters?",
  "Answer Ranil Wickremesinghe experienced a 14% increase in support among middle-income voters.",
  "Question How did support for Anura Dissanayake change among older adults?",
  "Answer Support for Anura Dissanayake decreased by 2% among older adults.",
  "Question Which candidate saw a 5-point increase in support among estate/Indian Tamil voters?",
  "Answer Support for Anura Dissanayake increased by 5 points among estate/Indian Tamil voters.",
  "Question How did Sajith Premadasa’s support change among younger voters aged 18-29?",
  "Answer Support for Sajith Premadasa increased by 12% among younger voters aged 18-29.",
  "Question Which demographic saw the smallest change in support for Ranil Wickremesinghe?",
  "Answer Support for Ranil Wickremesinghe saw the smallest change among Muslim voters, remaining at 0%.",
  "Question How did support for a generic SLPP candidate change among voters who supported Gotabaya Rajapakse in 2019?",
  "Answer Support for a generic SLPP candidate fell by 9% among voters who supported Gotabaya Rajapakse in 2019.",
  "Question Which candidate had the largest increase in support from female voters?",
  "Answer Ranil Wickremesinghe had the largest increase in support from female voters, with a 17% rise.",
  "Question How did support for Anura Dissanayake change among poor voters?",
  "Answer Support for Anura Dissanayake decreased by 4% among poor voters.",
  "Question Which candidate saw a 5-point increase in support among estate/Indian Tamil voters?",
  "Answer Support for Anura Dissanayake increased by 5 points among estate/Indian Tamil voters.",
  "Question How did support for Sajith Premadasa change among Muslim voters?",
  "Answer Support for Sajith Premadasa increased by 4% among Muslim voters.",
  "Question Which candidate experienced the smallest increase in support from female voters?",
  "Answer Sajith Premadasa experienced the smallest increase in support from female voters, with a 3% rise.",
  "Question How did support for Ranil Wickremesinghe change among voters who supported Sajith Premadasa in 2019?",
  "Answer Support for Ranil Wickremesinghe increased by 8% among voters who supported Sajith Premadasa in 2019.",
  "Question Which candidate experienced the largest drop in support among older adults?",
  "Answer Support for a generic SLPP candidate saw the largest drop among older adults, with a 13-point decrease.",
  "Question How did support for Anura Dissanayake change among SL Tamil voters?",
  "Answer Support for Anura Dissanayake increased by 5% among SL Tamil voters.",
  "Question Which demographic saw a decrease in support for Sajith Premadasa?",
  "Answer Support for Sajith Premadasa decreased among older adults, with a 9-point drop.",
  "Question How did support for Ranil Wickremesinghe change among voters with a negative view of the Aragalaya?",
  "Answer Support for Ranil Wickremesinghe increased by 16% among voters with a negative view of the Aragalaya.",
  "Question Which candidate saw an increase in support from anti-Aragalaya voters?",
  "Answer Ranil Wickremesinghe saw a 26-point increase in support from anti-Aragalaya voters.",
  "Question How did support for Anura Dissanayake change among middle-income voters?",
  "Answer Support for Anura Dissanayake decreased by 6% among middle-income voters.",
  "Question Which demographic saw the smallest increase in support for Ranil Wickremesinghe?",
  "Answer Support for Ranil Wickremesinghe saw the smallest increase among estate/Indian Tamil voters, with a 2% rise.",
  "Question How did support for Sajith Premadasa change among voters who supported Gotabaya Rajapakse in 2019?",
  "Answer Support for Sajith Premadasa decreased by 4% among voters who supported Gotabaya Rajapakse in 2019.",
  "Question Which candidate had the largest increase in support from younger voters aged 18-29?",
  "Answer Sajith Premadasa had the largest increase in support from younger voters aged 18-29, with a 12% rise.",
  "Question How did support for Ranil Wickremesinghe change among poor voters?",
  "Answer Support for Ranil Wickremesinghe increased by 8% among poor voters.",
  "Question Which demographic saw a decrease in support for Sajith Premadasa?",
  "Answer Support for Sajith Premadasa decreased among older adults, with a 9-point drop.",
  "Question How did support for a generic SLPP candidate change among voters who supported Gotabaya Rajapakse in 2019?",
  "Answer Support for a generic SLPP candidate fell by 9% among voters who supported Gotabaya Rajapakse in 2019.",
  "Question Which candidate experienced an increase in support among middle-income voters?",
  "Answer Ranil Wickremesinghe experienced a 14% increase in support among middle-income voters.",
  "Question How did support for Anura Dissanayake change among older adults?",
  "Answer Support for Anura Dissanayake decreased by 2% among older adults.",
  "Question Which candidate saw a 5-point increase in support among estate/Indian Tamil voters?",
  "Answer Support for Anura Dissanayake increased by 5 points among estate/Indian Tamil voters.",
  "Question How did Sajith Premadasa’s support change among younger voters aged 18-29?",
  "Answer Support for Sajith Premadasa increased by 12% among younger voters aged 18-29.",
  "Question Which demographic saw the smallest change in support for Ranil Wickremesinghe?",
  "Answer Support for Ranil Wickremesinghe saw the smallest change among Muslim voters, remaining at 0%.",
  "Question How did support for a generic SLPP candidate change among voters who supported Gotabaya Rajapakse in 2019?",
  "Answer Support for a generic SLPP candidate fell by 9% among voters who supported Gotabaya Rajapakse in 2019.",
  "Question Which candidate had the largest increase in support from female voters?",
  "Answer Ranil Wickremesinghe had the largest increase in support from female voters, with a 17% rise.",
  "Question who will be the winner",
  "Answer ")

# Function to get predictions from Gemini AI model
def get_prediction(input_text):
    try:
        # Append the "Who will win?" prompt to the user's input
        prompt = f"{input_text}\nGive me the winning chance in order in list?"
        
        response = model.generate_content(
            [prompt],
            safety_settings={
                HarmCategory.HARM_CATEGORY_HATE_SPEECH: HarmBlockThreshold.BLOCK_NONE,
                HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: HarmBlockThreshold.BLOCK_NONE,
            }
        )
        return response.text
    except Exception as e:
        st.error(f"Error generating predictions: {e}")
        return None

# Button to trigger the prediction
if st.button("Predict Election Outcome"):
    st.write("Fetching prediction from Gemini AI model...")
    prediction = get_prediction(input_data)
    
    # Display the prediction if successful
    if prediction:
        st.subheader("Election Prediction Results")
        st.write(prediction)
    else:
        st.error("No prediction available. Check your input data or the API.")